# Generated by Django 6.0.3 on 2026-03-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0003_alter_task_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Пояснение к задаче')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Реальная дата выполнения'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Плановая дата выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('pending', 'Не выполнено'), ('completed', 'Выполнено'), ('overdue', 'Просрочено')], default='pending', max_length=10, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='task_list.taskcontent', verbose_name='Содержимое задачи'),
        ),
    ]
