# Generated by Django 6.0.3 on 2026-03-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0004_taskcontent_task_completion_date_task_planned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснение к задаче'),
        ),
        migrations.DeleteModel(
            name='TaskContent',
        ),
    ]
