# Generated by Django 6.0.3 on 2026-03-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0005_alter_task_content_delete_taskcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Статус выполнения'),
        ),
    ]
