# Generated by Django 6.0.3 on 2026-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tg',
            field=models.CharField(blank=True, null=True, verbose_name='Имя пользователя в Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tg_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
